title: Sorry! 在线生成
header: 在线生成Sorry,动图

page_index:   public/index.html
page_404:     public/404.html
page_invalid: public/invalid.html

template_video:     resource/sorry.mp4
template_subtitle:  resource/sorry.erb
template_sentences: 9

server_ip:   0.0.0.0
server_port: 80

# useless, reserved for future use
cache_mode: local

# use to storage generated .ass file
temp_folder: temp/

# means public/cache/
cache_folder: cache/

max_jobs: 8